# Basic plugin options.
message-prefix: "&c&lZombie Mayhem&7&l>>"
boss-bar-message: "&b&lTest"

# Lobby world: Use /zm setspawn lobby to set the spawn in the specified world.
lobby-world:
  name: "world"

# Game Options
minimum-players: 1
maximum-players: 10
game-timer: 300
